FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore "MailSharp.slnx"
RUN dotnet publish "MailSharp.Worker/MailSharp.Worker.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/runtime:10.0 AS final
WORKDIR /app
ENV TZ=America/Fortaleza
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "MailSharp.Worker.dll"]